language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
stages:
  - name: test
#  - name: deploy
#    if: branch = master
jobs:
  include:
    - stage: test
      install:
        - pip install -r requirements-dev.txt
        - make install
      script:
        - ./coverage.sh
        - make lint
#    - stage: deploy
#      script: ./deploy
