language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
#stages:
#  - name: test
#  - name: deploy
#    if: branch = master

install:
  - pip install -r requirements.txt
  - make install
script:
  - ./coverage.sh
  - make lint

#jobs:
#  include:
#    - stage: test
#    - stage: deploy
#      script: ./deploy
